app_name="UserManagementService"

[front_end]
views_path="./front-end_test/dist"
templates_path="./templates_test"
template_delimiter_start="<<"
template_delimiter_end=">>"

[web_server]
ip="127.0.0.1"
port=7000
stop_url="/stop-server"
restart_url="/restart-server"
auth_key="umsAuthKey"
mode="DEBUG"

[[auth_databases]]
ip="127.0.0.1"
port=27017
database_name="authuser_db"
max_batch_size=1000

[log_config]
level="TRACE"
path="ums_logs"
days=100